# This code was generated by a large language model.
# It is not intended for production use.

def hello_world():
    """
    This function prints "Hello, World!" to the console.
    It is a classic example of a simple program.
    """
    print("Hello, World!")

# This code was generated by Copilot.
def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)
